# Generated by Django 3.0.6 on 2020-05-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('index', models.IntegerField()),
                ('budget', models.BigIntegerField()),
                ('genres', models.CharField(max_length=264)),
                ('homepage', models.CharField(max_length=264)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('keywords', models.CharField(max_length=264)),
                ('original_language', models.CharField(max_length=264)),
                ('original_title', models.CharField(max_length=264)),
                ('overview', models.CharField(max_length=264)),
                ('popularity', models.FloatField()),
                ('production_companies', models.CharField(max_length=264)),
                ('production_countries', models.CharField(max_length=264)),
                ('release_data', models.DateField()),
                ('revenue', models.BigIntegerField()),
                ('runtime', models.IntegerField()),
                ('spoken_languages', models.CharField(max_length=264)),
                ('status', models.CharField(max_length=264)),
                ('tagline', models.CharField(max_length=264)),
                ('title', models.CharField(max_length=264)),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('cast', models.CharField(max_length=264)),
                ('crew', models.CharField(max_length=264)),
                ('director', models.CharField(max_length=264)),
                ('time_created', models.TimeField()),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='movies',
        ),
    ]
