# Generated by Django 3.0.6 on 2020-05-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200506_1521'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='movie',
            new_name='movies',
        ),
    ]
