# Generated by Django 3.0.6 on 2020-05-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200506_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='cast',
            field=models.CharField(max_length=528),
        ),
        migrations.AlterField(
            model_name='movies',
            name='crew',
            field=models.CharField(max_length=528),
        ),
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.CharField(max_length=528),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genres',
            field=models.CharField(max_length=528),
        ),
        migrations.AlterField(
            model_name='movies',
            name='homepage',
            field=models.CharField(max_length=528),
        ),
        migrations.AlterField(
            model_name='movies',
            name='keywords',
            field=models.CharField(max_length=528),
        ),
        migrations.AlterField(
            model_name='movies',
            name='original_language',
            field=models.CharField(max_length=528),
        ),
        migrations.AlterField(
            model_name='movies',
            name='original_title',
            field=models.CharField(max_length=528),
        ),
        migrations.AlterField(
            model_name='movies',
            name='overview',
            field=models.CharField(max_length=528),
        ),
        migrations.AlterField(
            model_name='movies',
            name='production_companies',
            field=models.CharField(max_length=528),
        ),
        migrations.AlterField(
            model_name='movies',
            name='production_countries',
            field=models.CharField(max_length=528),
        ),
        migrations.AlterField(
            model_name='movies',
            name='spoken_languages',
            field=models.CharField(max_length=528),
        ),
        migrations.AlterField(
            model_name='movies',
            name='status',
            field=models.CharField(max_length=528),
        ),
        migrations.AlterField(
            model_name='movies',
            name='tagline',
            field=models.CharField(max_length=528),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=528),
        ),
    ]
