# Generated by Django 3.0.6 on 2020-05-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200506_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='cast',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='production_companies',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='production_countries',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='spoken_languages',
            field=models.TextField(),
        ),
    ]
