# Generated by Django 3.0.6 on 2020-05-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20200506_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='crew',
            field=models.TextField(),
        ),
    ]
