# Generated by Django 3.0.6 on 2020-05-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20200506_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='overview',
            field=models.TextField(),
        ),
    ]
