# Generated by Django 3.0.6 on 2020-05-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movies_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='choices',
            fields=[
                ('submission_id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_1', models.CharField(max_length=528)),
                ('movie_2', models.CharField(max_length=528)),
                ('movie_3', models.CharField(max_length=528)),
            ],
        ),
        migrations.DeleteModel(
            name='movies_choices',
        ),
    ]
